---
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Role:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: "Allow"
          Action:
          - "sts:AssumeRole"
          Principal:
            Service:
            - "lambda.amazonaws.com"
        Version: "2012-10-17"
      ManagedPolicyArns:
      - Fn::Join:
        - ""
        - - "arn:"
          - Ref: "AWS::Partition"
          - ":iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
      Path: "/"
      Policies:
      - PolicyDocument:
          Statement:
          - Effect: "Allow"
            Action:
            - "logs:CreateLogStream"
            Resource:
            - Fn::Join:
              - ""
              - - "arn:"
                - Ref: "AWS::Partition"
                - ":logs:"
                - Ref: "AWS::Region"
                - ":"
                - Ref: "AWS::AccountId"
                - ":log-group:/aws/lambda/kt-everywhere-service-demo-definition:*"
          - Effect: "Allow"
            Action:
            - "logs:PutLogEvents"
            Resource:
            - Fn::Join:
              - ""
              - - "arn:"
                - Ref: "AWS::Partition"
                - ":logs:"
                - Ref: "AWS::Region"
                - ":"
                - Ref: "AWS::AccountId"
                - ":log-group:/aws/lambda/kt-everywhere-service-demo-definition:*"
                - ":*"
          - Effect: "Allow"
            Action:
            - "execute-api:ManageConnections"
            Resource:
            - "arn:aws:execute-api:*:*:*/@connections/*"
          Version: "2012-10-17"
        PolicyName: "demo-kt-everywhere-service-lambda"
  LogGroupMyFunction:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: "/aws/lambda/kt-everywhere-service-demo-myFunction"
  FunctionMyFunction:
    Type: "AWS::Lambda::Function"
    DependsOn:
    - "LogGroupMyFunction"
    - "Role"
    Properties:
      Code:
        S3Bucket: "lambda-cf-bucket2"
        S3Key: "kt-everywhere/2355262654871-2019-09-10-02:20:59/src.zip"
      Handler: "index.handle"
      Role:
        Fn::GetAtt:
        - "Role"
        - "Arn"
      Runtime: "nodejs8.10"
  RestApi:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: "demo-kt-everywhere-service"
  ApiGatewayResourceping:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId:
        Fn::GetAtt:
        - "RestApi"
        - "RootResourceId"
      PathPart: "ping"
      RestApiId:
        Ref: "RestApi"
  MethodpingGET:
    Type: "AWS::ApiGateway::Method"
    Properties:
      HttpMethod: "GET"
      ResourceId:
        Ref: "ApiGatewayResourceping"
      RestApiId:
        Ref: "RestApi"
      ApiKeyRequired: false
      AuthorizationType: "None"
      Integration:
        IntegrationHttpMethod: "POST"
        Type: "AWS_PROXY"
        Uri:
          Fn::Join:
          - ""
          - - "arn:"
            - Ref: "AWS::Partition"
            - ":apigateway:"
            - Ref: "AWS::Region"
            - ":lambda:path/2015-03-31/functions/"
            - Fn::GetAtt:
              - "FunctionMyFunction"
              - "Arn"
            - "/invocations"
      MethodResponses: []
      RequestParameters: {}
  ApiDeploymentc2f88f5864e54ca29e27953b1390926c:
    Type: "AWS::ApiGateway::Deployment"
    DependsOn:
    - "MethodpingGET"
    Properties:
      RestApiId:
        Ref: "RestApi"
      StageName: "demo"
  Permission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName:
        Fn::GetAtt:
        - "FunctionMyFunction"
        - "Arn"
      Principal:
        Fn::Join:
        - ""
        - - "apigateway."
          - Ref: "AWS::URLSuffix"
      SourceArn:
        Fn::Join:
        - ""
        - - "arn:"
          - Ref: "AWS::Partition"
          - ":execute-api:"
          - Ref: "AWS::Region"
          - ":"
          - Ref: "AWS::AccountId"
          - ":"
          - Ref: "RestApi"
          - "/*/*"
Outputs:
  ServiceEndpoint:
    Value:
      Fn::Join:
      - ""
      - - "https://"
        - Ref: "RestApi"
        - ".execute-api."
        - Ref: "AWS::Region"
        - "."
        - Ref: "AWS::URLSuffix"
        - "/demo"
    Description: "URL of the service"
