---
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Role:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: "Allow"
          Action:
          - "sts:AssumeRole"
          Principal:
            Service:
            - "lambda.amazonaws.com"
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Path: "/"
  Function:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        ZipFile: "exports.handle = (event, context, callback) => { console.log(\"\
          hello world!\"); callback(null); }"
      Handler: "index.handle"
      Role:
        Fn::GetAtt:
        - "Role"
        - "Arn"
      Runtime: "nodejs8.10"
      Environment:
        Variables:
          ABC: "def"
